apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap1.2
data:
  BACKGROUND_COLOR: "#FF0000"

---

apiVersion: v1
kind: Service
metadata: 
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: tayeblagha/configmap
        ports:
        - containerPort: 8080
        env:
          - name: BACKGROUND_COLOR
            valueFrom:
              configMapKeyRef:
                name: myconfigmap1.2
                key: BACKGROUND_COLOR
        resources:
          requests:
            memory: "150Mi"
            cpu: "50m"
          limits:
            memory: "250Mi"
            cpu: "100m"
        
